env:
  - CGO_ENABLED=0
  - PROJECT=github.com/cloudradar-monitoring/rport
builds:
  - id: rport
    main: ./cmd/rport
    binary: rport
    ldflags:
      - "-s -w -X {{.Env.PROJECT}}/share.BuildVersion={{.Version}}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
      - s390x
      - ppc64
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: amd64
      # TODO: remove when https://github.com/go-ole/go-ole/issues/202 will be fixed
      - goos: windows
        goarch: arm
      - goos: linux
        goarch: ppc64
  - id: rport-linux-amd64
    main: ./cmd/rport
    binary: rport
    ldflags:
      - "-s -w -X {{.Env.PROJECT}}/share.BuildVersion={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
  - id: rportd
    main: ./cmd/rportd
    binary: rportd
    ldflags:
      - "-s -w -X {{.Env.PROJECT}}/share.BuildVersion={{.Version}}"
      #- "-extldflags '-static'"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: rport-only
    builds:
      - rport
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - rport.example.conf
  - id: all
    builds:
      - rport-linux-amd64
      - rportd
    replacements:
      linux: Linux
      amd64: x86_64
    files:
      - rport.example.conf
      - rportd.example.conf
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
release:
  github:
    owner: cloudradar-monitoring
    name: rport
  draft: true
